---
- name: Generate SSH key for Bitbucket
  openssh_keypair:
    path: ~/.ssh/bitbucket_rsa
    type: rsa
    size: 2048
  register: ssh_key

- name: Display public key
  debug:
    msg: "Add this public key to Bitbucket: {{ ssh_key.public_key }}"
  when: ssh_key.changed

- name: Configure SSH for Bitbucket
  blockinfile:
    path: ~/.ssh/config
    create: yes
    block: |
      Host dsu-bitbucket.nestle.biz
        HostName dsu-bitbucket.nestle.biz
        User git
        IdentityFile ~/.ssh/bitbucket_rsa