---
# Verification task to ensure all modules are properly configured
- name: Verify community.general collection is available
  ansible.builtin.debug:
    msg: "Community.general collection is required for composer and npm modules"

- name: Test git module functionality
  ansible.builtin.git:
    repo: "https://github.com/ansible/ansible.git"
    dest: "/tmp/ansible-test"
    version: "stable-2.9"
    depth: 1
  become: true
  failed_when: false
  changed_when: false

- name: Clean up test repository
  ansible.builtin.file:
    path: "/tmp/ansible-test"
    state: absent
  become: true

- name: Display refactoring completion message
  ansible.builtin.debug:
    msg: |
      ✅ TAP Ansible Role Refactoring Complete!
      
      All shell commands have been replaced with proper Ansible modules:
      - ansible.builtin.git for Git operations
      - community.general.composer for PHP dependencies
      - community.general.npm for Node.js operations
      - ansible.builtin.file for file/directory operations
      - ansible.builtin.copy for file copying
      - ansible.builtin.command for single commands
      - ansible.builtin.find for file searching
      
      The role is now production-ready and follows Ansible best practices!