---
# handlers file for nespresso_ansible_role_tap

- name: Restart Supervisor
  ansible.builtin.service:
    name: supervisord
    state: restarted
  become: true
  register: supervisor_restart
  failed_when: supervisor_restart.failed and supervisor_restart.msg is defined and 'not found' in supervisor_restart.msg